verify_jwt = false

# Default CORS headers applied to all responses
[headers]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "POST, OPTIONS"
Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
Access-Control-Max-Age = "86400"


